apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openmeals.fullname" . }}-worker
  labels:
    {{- include "openmeals.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicaCount }}
  selector:
    matchLabels:
      {{- include "openmeals.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "openmeals.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: {{ include "openmeals.workerImage" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "openmeals.fullname" . }}
            - secretRef:
                name: {{ .Values.existingSecret }}
          resources:
            {{- toYaml .Values.worker.resources | nindent 12 }}
