"""add vectors

Revision ID: 295990d065d8
Revises: 467b6206bb7d
Create Date: 2026-03-21 15:12:20.075579+00:00

"""

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "295990d065d8"
down_revision: str | Sequence[str] | None = "467b6206bb7d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("drinks", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_index(
        "ix_drinks_embedding",
        "drinks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.add_column("foods", sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True))
    op.create_index(
        "ix_foods_embedding",
        "foods",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_foods_embedding",
        table_name="foods",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_column("foods", "embedding")
    op.drop_index(
        "ix_drinks_embedding",
        table_name="drinks",
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    op.drop_column("drinks", "embedding")
    op.execute("DROP EXTENSION IF EXISTS vector")
    # ### end Alembic commands ###
