"""add name to users

Revision ID: a5334e55f04f
Revises: 295990d065d8
Create Date: 2026-03-22 00:42:43.819737+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a5334e55f04f'
down_revision: Union[str, Sequence[str], None] = '295990d065d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('users', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
