"""create tables

Revision ID: acc01156a51a
Revises:
Create Date: 2026-03-21 11:38:58.626941+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "acc01156a51a"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drinks",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vitamins", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("minerals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nutrients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("curated", sa.Boolean(), nullable=True),
        sa.Column("ph", sa.Float(), nullable=False),
        sa.Column("is_carbonated", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index("ix_drinks_minerals", "drinks", ["minerals"], unique=False, postgresql_using="gin")
    op.create_index("ix_drinks_nutrients", "drinks", ["nutrients"], unique=False, postgresql_using="gin")
    op.create_index("ix_drinks_vitamins", "drinks", ["vitamins"], unique=False, postgresql_using="gin")

    op.create_table(
        "foods",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("vitamins", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("minerals", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("nutrients", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("creator_id", sa.String(length=26), nullable=True),
        sa.Column("curated", sa.Boolean(), nullable=True),
        sa.Column("proteins", sa.Float(), nullable=False),
        sa.Column("carbs", sa.Float(), nullable=False),
        sa.Column("fats", sa.Float(), nullable=False),
        sa.Column("fibers", sa.Float(), nullable=False),
        sa.Column("sugars", sa.Float(), nullable=False),
        sa.Column("energy", sa.Float(), nullable=False),
        sa.Column("glycemic_index", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )

    op.create_index("ix_foods_minerals", "foods", ["minerals"], unique=False, postgresql_using="gin")
    op.create_index("ix_foods_nutrients", "foods", ["nutrients"], unique=False, postgresql_using="gin")
    op.create_index("ix_foods_vitamins", "foods", ["vitamins"], unique=False, postgresql_using="gin")

    op.create_table(
        "users",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "meals",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "id"),  # IMPORTANT - user_id first for sharding
    )

    op.create_table(
        "periodic_summaries",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("period", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("started", sa.Date(), nullable=False),
        sa.Column("computed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.Text(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "id"),  # IMPORTANT - user_id first for sharding
        sa.UniqueConstraint("user_id", "period", "started", name="uq_periodic_summaries_user_period_started"),
    )

    op.create_table(
        "user_oauth",
        sa.Column("provider", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sub", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("provider", "sub"),
    )

    op.create_index("ix_user_oauth_user_id", "user_oauth", ["user_id"], unique=False)

    op.create_table(
        "user_profiles",
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("birthday", sa.Date(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=False),
        sa.Column("height", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id"),
    )

    op.create_table(
        "meal_drinks",
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("meal_id", sa.String(length=26), nullable=False),
        sa.Column("drink_id", sa.String(length=26), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drink_id"],
            ["drinks.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "meal_id", "drink_id"),  # IMPORTANT - user_id first for sharding
    )

    op.create_table(
        "meal_foods",
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("meal_id", sa.String(length=26), nullable=False),
        sa.Column("food_id", sa.String(length=26), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["food_id"],
            ["foods.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "meal_id", "food_id"),  # IMPORTANT - user_id first for sharding
    )

    op.create_table(
        "meal_summaries",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("created", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_id", sa.String(length=26), nullable=False),
        sa.Column("meal_id", sa.String(length=26), nullable=False),
        sa.Column("computed", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("model_version", sa.String(), nullable=True),
        sa.Column("data", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("user_id", "id"),  # IMPORTANT - user_id first for sharding
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("meal_summaries")
    op.drop_table("meal_foods")
    op.drop_table("meal_drinks")
    op.drop_table("user_profiles")
    op.drop_index("ix_user_oauth_user_id", table_name="user_oauth")
    op.drop_table("user_oauth")
    op.drop_table("periodic_summaries")
    op.drop_table("meals")
    op.drop_table("users")
    op.drop_index("ix_foods_vitamins", table_name="foods", postgresql_using="gin")
    op.drop_index("ix_foods_nutrients", table_name="foods", postgresql_using="gin")
    op.drop_index("ix_foods_minerals", table_name="foods", postgresql_using="gin")
    op.drop_table("foods")
    op.drop_index("ix_drinks_vitamins", table_name="drinks", postgresql_using="gin")
    op.drop_index("ix_drinks_nutrients", table_name="drinks", postgresql_using="gin")
    op.drop_index("ix_drinks_minerals", table_name="drinks", postgresql_using="gin")
    op.drop_table("drinks")
    # ### end Alembic commands ###
